### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'int' and 'method'

### ISSUE THREAD

**Issue by donghhan** [donghhan/letsh-api#2]
# What I tried to do 

Calculating the total rating score based on 6 average individual scores (`cleanliness`, `accuracy`, `location`, `commuinication`, `check_in`, `value`)

# What I tried

```py
class Review(CommonDateTimeModel):
    # ...
    def average_rating(self):
        rating_fields = [
            self.average_cleanliness,
            self.average_accuracy,
            self.average_location,
            self.average_communication,
            self.average_check_in,
            self.average_value,
        ]

        rating_values = [rating for rating in rating_fields if rating is not None]

        if rating_values:
            total_scores = sum(rating_values)
            average_score = round(total_scores / len(rating_values), 2)
            return average_score

        return None

    average_rating.short_description = _("Average Rating")
```

# Error that I got

```
Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/admin/reviews/review/

Django Version: 4.2.3
Python Version: 3.11.4
Installed Applications:
['cities_light',
 'rest_framework',
 'drf_yasg',
 'corsheaders',
 'rest_framework_simplejwt',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'users.apps.UsersConfig',
 'rooms.apps.RoomsConfig',
 'wishlists.apps.WishlistsConfig',
 'reservations.apps.ReservationsConfig',
 'common.apps.CommonConfig',
 'categories.apps.CategoriesConfig',
 'tokens.apps.TokensConfig',
 'photos.apps.PhotosConfig',
 'reviews.apps.ReviewsConfig']
Installed Middleware:
['corsheaders.middleware.CorsMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']


Template error:
In template /Users/apensia/.local/share/virtualenvs/letsh-api-VerA_6n_/lib/python3.11/site-packages/django/contrib/admin/templates/admin/change_list.html, error at line 68
   unsupported operand type(s) for +: 'int' and 'method'
   58 :         {% block search %}{% search_form cl %}{% endblock %}
   59 :         {% block date_hierarchy %}{% if cl.date_hierarchy %}{% date_hierarchy cl %}{% endif %}{% endblock %}
   60 : 
   61 :         <form id="changelist-form" method="post"{% if cl.formset and cl.formset.is_multipart %} enctype="multipart/form-data"{% endif %} novalidate>{% csrf_token %}
   62 :         {% if cl.formset %}
   63 :           <div>{{ cl.formset.management_form }}</div>
   64 :         {% endif %}
   65 : 
   66 :         {% block result_list %}
   67 :           {% if action_form and actions_on_top and cl.show_admin_actions %}{% admin_actions %}{% endif %}
   68 :            {% result_list cl %} 
   69 :           {% if action_form and actions_on_bottom and cl.show_admin_actions %}{% admin_actions %}{% endif %}
   70 :         {% endblock %}
   71 :         {% block pagination %}{% pagination cl %}{% endblock %}
   72 :         </form>
   73 :       </div>
   74 :       {% block filters %}
   75 :         {% if cl.has_filters %}
   76 :           <div id="changelist-filter">
   77 :             <h2>{% translate 'Filter' %}</h2>
   78 :             {% if cl.has_active_filters %}<h3 id="changelist-filter-clear">


Traceback (most recent call last):
  File "/Users/apensia/.local/share/virtualenvs/letsh-api-VerA_6n_/lib/python3.11/site-packages/django/db/models/options.py", line 681, in get_field
    return self.fields_map[field_name]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^

During handling of the above exception ('average_rating'), another exception occurred:
  File "/Users/apensia/.local/share/virtualenvs/letsh-api-VerA_6n_/lib/python3.11/site-packages/django/contrib/admin/utils.py", line 272, in lookup_field
    f = _get_non_gfk_field(opts, name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apensia/.local/share/virtualenvs/letsh-api-VerA_6n_/lib/python3.11/site-packages/django/contrib/admin/utils.py", line 303, in _get_non_gfk_field
    field = opts.get_field(name)
            ^^^^^^^^^^^^^^^^^^^^
  File "/Users/apensia/.local/share/virtualenvs/letsh-api-VerA_6n_/lib/python3.11/site-packages/django/db/models/options.py", line 683, in get_field
    raise FieldDoesNotExist(
    ^

During handling of the above exception (Review has no field named 'average_rating'), another exception occurred:
  File "/Users/apensia/.local/share/virtualenvs/letsh-api-VerA_6n_/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apensia/.local/share/virtualenvs/letsh-api-VerA_6n_/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/apensia/.local/share/virtualenvs/letsh-api-VerA_6n_/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apensia/.local/share/virtualenvs/letsh-api-VerA_6n_/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apensia/.local/share/virtualenvs/letsh-api-VerA_6n_/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apensia/.local/share/virtualenvs/letsh-api-VerA_6n_/lib/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apensia/.local/share/virtualenvs/letsh-api-VerA_6n_/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apensia/.local/share/virtualenvs/letsh-api-VerA_6n_/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apensia/.local/share/virtualenvs/letsh-api-VerA_6n_/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apensia/.local/share/virtualenvs/letsh-api-VerA_6n_/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/apensia/.local/share/virtualenvs/letsh-api-VerA_6n_/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apensia/.local/share/virtualenvs/letsh-api-VerA_6n_/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apensia/.local/share/virtualenvs/letsh-api-VerA_6n_/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apensia/.local/share/virtualenvs/letsh-api-VerA_6n_/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apensia/.local/share/virtualenvs/letsh-api-VerA_6n_/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/apensia/.local/share/virtualenvs/letsh-api-VerA_6n_/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apensia/.local/share/virtualenvs/letsh-api-VerA_6n_/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apensia/.local/share/virtualenvs/letsh-api-VerA_6n_/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apensia/.local/share/virtualenvs/letsh-api-VerA_6n_/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apensia/.local/share/virtualenvs/letsh-api-VerA_6n_/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/apensia/.local/share/virtualenvs/letsh-api-VerA_6n_/lib/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apensia/.local/share/virtualenvs/letsh-api-VerA_6n_/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apensia/.local/share/virtualenvs/letsh-api-VerA_6n_/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apensia/.local/share/virtualenvs/letsh-api-VerA_6n_/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/apensia/.local/share/virtualenvs/letsh-api-VerA_6n_/lib/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apensia/.local/share/virtualenvs/letsh-api-VerA_6n_/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apensia/.local/share/virtualenvs/letsh-api-VerA_6n_/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apensia/.local/share/virtualenvs/letsh-api-VerA_6n_/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/apensia/.local/share/virtualenvs/letsh-api-VerA_6n_/lib/python3.11/site-packages/django/contrib/admin/templatetags/base.py", line 45, in render
    return super().render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apensia/.local/share/virtualenvs/letsh-api-VerA_6n_/lib/python3.11/site-packages/django/template/library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apensia/.local/share/virtualenvs/letsh-api-VerA_6n_/lib/python3.11/site-packages/django/contrib/admin/templatetags/admin_list.py", line 336, in result_list
    "results": list(results(cl)),
               ^^^^^^^^^^^^^^^^^
  File "/Users/apensia/.local/share/virtualenvs/letsh-api-VerA_6n_/lib/python3.11/site-packages/django/contrib/admin/templatetags/admin_list.py", line 312, in results
    yield ResultList(None, items_for_result(cl, res, None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apensia/.local/share/virtualenvs/letsh-api-VerA_6n_/lib/python3.11/site-packages/django/contrib/admin/templatetags/admin_list.py", line 303, in __init__
    super().__init__(*items)
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apensia/.local/share/virtualenvs/letsh-api-VerA_6n_/lib/python3.11/site-packages/django/contrib/admin/templatetags/admin_list.py", line 213, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apensia/.local/share/virtualenvs/letsh-api-VerA_6n_/lib/python3.11/site-packages/django/contrib/admin/utils.py", line 285, in lookup_field
    value = attr()
            ^^^^^^
  File "/Users/apensia/dev/letsh-api/reviews/models.py", line 119, in average_rating
    total_scores = sum(rating_values)
                   ^^^^^^^^^^^^^^^^^^

Exception Type: TypeError at /admin/reviews/review/
Exception Value: unsupported operand type(s) for +: 'int' and 'method'
```

**Comment by donghhan** [comment]
Forgot to call it for retrieving values:

```py
def average_total_rating(self):
        rating_fields = [
            self.average_cleanliness(),
            self.average_accuracy(),
            self.average_location(),
            self.average_communication(),
            self.average_check_in(),
            self.average_value(),
        ]

        rating_values = [eval(rating) for rating in rating_fields if rating is not None]

        if rating_values:
            total_scores = sum(rating_values)
            average_score = round(total_scores / len(rating_values), 2)
            return average_score

        return None
```
